import type { NavigationItem } from './types';

// This file now serves as a fallback or for initial seeding.
// The primary source of truth is the 'navigationItems' collection in Firestore.
export const defaultNavItems: NavigationItem[] = [
   {
    id: 'nav_my_work',
    label: 'nav.my_work',
    path: '/my-work',
    icon: 'Inbox',
    order: 0,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: null,
  },
  // --- GROUP 1: PROJECTS ---
  {
    id: 'nav_tasks_group',
    label: 'Projects', // Changed from 'Tasks'
    path: '',
    icon: 'ClipboardList',
    order: 1,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: null,
  },
  {
    id: 'nav_task_board',
    label: 'nav.board',
    path: '/dashboard',
    icon: 'KanbanSquare',
    order: 1.1,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_tasks_group',
  },
  {
    id: 'nav_list',
    label: 'All Tasks', // Changed from 'List'
    path: '/tasks',
    icon: 'List',
    order: 1.2,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_tasks_group',
  },
  {
    id: 'nav_task_schedule',
    label: 'nav.schedule',
    path: '/tasks/schedule',
    icon: 'CalendarClock',
    order: 1.3,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_tasks_group',
  },
  // --- GROUP 2: SOCIAL MEDIA ---
  {
    id: 'nav_social_media_group',
    label: 'nav.social_media',
    path: '',
    icon: 'Share2',
    order: 2,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: null,
  },
  {
    id: 'nav_social_media_list',
    label: 'nav.list_social_media',
    path: '/social-media/posts',
    icon: 'List',
    order: 2.1,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_social_media_group',
  },
   {
    id: 'nav_social_media_schedule',
    label: 'nav.schedule',
    path: '/social-media/schedule',
    icon: 'CalendarClock',
    order: 2.2,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_social_media_group',
  },
   {
    id: 'nav_social_media_calendar',
    label: 'nav.social_media_calendar',
    path: '/social-media/calendar',
    icon: 'CalendarDays',
    order: 2.3,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_social_media_group',
  },
  {
    id: 'nav_social_media_analytics',
    label: 'nav.analytics',
    path: '/social-media/analytics',
    icon: 'BarChart2',
    order: 2.4,
    roles: ['Super Admin', 'Manager'],
    parentId: 'nav_social_media_group',
  },
  {
    id: 'nav_social_media_integrations',
    label: 'nav.integrations',
    path: '/social-media/integrations',
    icon: 'Plug',
    order: 2.5,
    roles: ['Super Admin', 'Manager'],
    parentId: 'nav_social_media_group',
  },
  // --- GROUP 3: WEB ---
  {
    id: 'nav_web_group',
    label: 'Web',
    path: '',
    icon: 'Globe',
    order: 3,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: null,
  },
  {
    id: 'nav_web_articles_list',
    label: 'List Articles',
    path: '/web/articles',
    icon: 'List',
    order: 3.1,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_web_group',
  },
  {
    id: 'nav_web_schedule',
    label: 'Schedule',
    path: '/web/schedule',
    icon: 'CalendarClock',
    order: 3.2,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: 'nav_web_group',
  },
  // --- OTHER ---
  {
    id: 'nav_daily_checklist',
    label: 'nav.daily_checklist',
    path: '/daily-report',
    icon: 'ClipboardCheck',
    order: 4,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: null,
  },
  {
    id: 'nav_performance_analysis',
    label: 'nav.reports',
    path: '/reports',
    icon: 'FileText',
    order: 7,
    roles: ['Super Admin', 'Manager', 'Employee'],
    parentId: null,
  },
  {
    id: 'nav_guide',
    label: 'nav.guide',
    path: '/guide',
    icon: 'BookOpen',
    order: 8,
    roles: ['Super Admin', 'Manager', 'Employee', 'Client'],
    parentId: null,
  },
  // --- ADMIN & SETTINGS ---
  {
    id: 'nav_admin',
    label: 'nav.admin',
    path: '', // This is a folder
    icon: 'Shield',
    order: 10,
    roles: ['Super Admin', 'Manager'],
    parentId: null,
  },
  {
    id: 'nav_admin_dashboard',
    label: 'nav.admin_dashboard',
    path: '/admin/dashboard',
    icon: 'LayoutDashboard',
    order: 11,
    roles: ['Super Admin', 'Manager'],
    parentId: 'nav_admin',
  },
  {
    id: 'nav_admin_users',
    label: 'nav.users',
    path: '/admin/users',
    icon: 'Users',
    order: 12,
    roles: ['Super Admin', 'Manager'],
    parentId: 'nav_admin',
  },
  {
    id: 'nav_admin_data',
    label: 'nav.data',
    path: '/admin/data',
    icon: 'Database',
    order: 13,
    roles: ['Super Admin'],
    parentId: 'nav_admin',
  },
  {
    id: 'nav_settings',
    label: 'nav.settings',
    path: '', // This is a folder
    icon: 'Settings',
    order: 20,
    roles: ['Super Admin', 'Manager'],
    parentId: null,
  },
  {
    id: 'nav_settings_company',
    label: 'nav.company',
    path: '/admin/settings',
    icon: 'Building',
    order: 21,
    roles: ['Super Admin'],
    parentId: 'nav_settings',
  },
   {
    id: 'nav_settings_brands',
    label: 'nav.brands',
    path: '/admin/settings/brands',
    icon: 'Building2',
    order: 22,
    roles: ['Super Admin'],
    parentId: 'nav_settings',
  },
  {
    id: 'nav_settings_roles',
    label: 'nav.roles_permissions',
    path: '/admin/settings/roles',
    icon: 'KeyRound',
    order: 23,
    roles: ['Super Admin'],
    parentId: 'nav_settings',
  },
  {
    id: 'nav_settings_navigation',
    label: 'nav.navigation_settings',
    path: '/admin/settings/navigation',
    icon: 'SlidersHorizontal',
    order: 24,
    roles: ['Super Admin'],
    parentId: 'nav_settings',
  },
   {
    id: 'nav_settings_workflow',
    label: 'nav.workflow',
    path: '/admin/settings/workflow',
    icon: 'Workflow',
    order: 25,
    roles: ['Super Admin'],
    parentId: 'nav_settings',
  },
  {
    id: 'nav_settings_recurring',
    label: 'nav.recurring_tasks',
    path: '/admin/settings/recurring',
    icon: 'Repeat',
    order: 26,
    roles: ['Super Admin', 'Manager'],
    parentId: 'nav_settings',
  },
];
