
import type { NavigationItem } from './types';

export const defaultNavItems: NavigationItem[] = [
  {
    id: 'nav_task_board',
    label: 'Task Board',
    path: '/dashboard',
    icon: 'KanbanSquare',
    order: 1,
    roles: ['Super Admin', 'Manager', 'Employee'],
  },
  {
    id: 'nav_list',
    label: 'List',
    path: '/tasks',
    icon: 'ClipboardList',
    order: 2,
    roles: ['Super Admin', 'Manager', 'Employee'],
  },
  {
    id: 'nav_daily_checklist',
    label: 'Daily Checklist',
    path: '/daily-report',
    icon: 'ClipboardCheck',
    order: 3,
    roles: ['Super Admin', 'Manager', 'Employee'],
  },
   {
    id: 'nav_settings_recurring',
    label: 'Recurring Tasks',
    path: '/tasks/recurring',
    icon: 'Repeat',
    order: 4,
    roles: ['Super Admin', 'Manager'],
  },
  {
    id: 'nav_calendar',
    label: 'Calendar',
    path: '/calendar',
    icon: 'CalendarDays',
    order: 5,
    roles: ['Super Admin', 'Manager', 'Employee'],
  },
  {
    id: 'nav_performance_analysis',
    label: 'Performance Analysis',
    path: '/reports',
    icon: 'FileText',
    order: 6,
    roles: ['Super Admin', 'Manager', 'Employee'],
  },
  {
    id: 'nav_admin_dashboard',
    label: 'Admin Dashboard',
    path: '/admin/dashboard',
    icon: 'LayoutDashboard',
    order: 10,
    roles: ['Super Admin', 'Manager'],
  },
  {
    id: 'nav_admin_users',
    label: 'Users',
    path: '/admin/users',
    icon: 'Users',
    order: 11,
    roles: ['Super Admin', 'Manager'],
  },
  {
    id: 'nav_admin_data',
    label: 'Data',
    path: '/admin/data',
    icon: 'Database',
    order: 12,
    roles: ['Super Admin'],
  },
  {
    id: 'nav_settings_company',
    label: 'Company',
    path: '/admin/settings',
    icon: 'Building',
    order: 20,
    roles: ['Super Admin'],
  },
   {
    id: 'nav_settings_brands',
    label: 'Brands',
    path: '/admin/settings/brands',
    icon: 'Building2',
    order: 21,
    roles: ['Super Admin'],
  },
  {
    id: 'nav_settings_roles',
    label: 'Roles & Permissions',
    path: '/admin/settings/roles',
    icon: 'KeyRound',
    order: 22,
    roles: ['Super Admin', 'Manager'],
  },
  {
    id: 'nav_settings_navigation',
    label: 'Navigation',
    path: '/admin/settings/navigation',
    icon: 'SlidersHorizontal',
    order: 24,
    roles: ['Super Admin', 'Manager'],
  },
   {
    id: 'nav_settings_workflow',
    label: 'Workflow',
    path: '/admin/settings/workflow',
    icon: 'Workflow',
    order: 25,
    roles: ['Super Admin'],
  },
];
